# Generated by Django 4.0.1 on 2022-01-31 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaveToBoard',
        ),
    ]
