# Generated by Django 4.0.1 on 2022-01-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='image',
        ),
        migrations.AddField(
            model_name='pin',
            name='file',
            field=models.FileField(default=1, upload_to='pins'),
            preserve_default=False,
        ),
    ]
