# Generated by Django 4.0.1 on 2022-01-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='link',
            field=models.CharField(max_length=250),
        ),
    ]
