# Generated by Django 4.0.1 on 2022-01-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0001_initial'),
        ('boards', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='pin',
        ),
        migrations.AddField(
            model_name='board',
            name='pins',
            field=models.ManyToManyField(related_name='pins', to='pins.Pin'),
        ),
    ]
