# Generated by Django 4.0.1 on 2022-01-31 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_board_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='board',
            name='cover',
            field=models.ImageField(default='boards/default.png', upload_to='boards'),
        ),
    ]
