# Generated by Django 4.0.1 on 2022-01-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0002_alter_pin_link'),
        ('boards', '0003_remove_board_pin_board_pins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='pins',
            field=models.ManyToManyField(blank=True, related_name='pins', to='pins.Pin'),
        ),
    ]
