# Generated by Django 4.0.1 on 2022-01-31 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_board_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='description',
            field=models.CharField(blank=True, default=11, max_length=250),
            preserve_default=False,
        ),
    ]
